### ISSUE TITLE
PyVISA-py 0.5.0 requires pyvisa>=1.11.0

### ISSUE THREAD

**Issue by davidfokkema** [conda-forge/pyvisa-py-feedstock#17]
A `conda update --all` broke my environment. After the release of pyvisa-py 0.5.0 the dependency requirements were fixed, see pyvisa/pyvisa-py@112c577131c516ac066c19b86994ff159cfe7451. This package (version 0.5.0) should require pyvisa>=1.11.0. Thanks!

**Comment by mtsolmn** [comment]
thanks for reporting. The problem is pyvisa needs to be updated on conda-forge and the requirement on the actually setup.cfg of pyvisa-py needs to be updated, which is a separate repository. I've already reported the issue there and it's being taken care.

**Comment by davidfokkema** [comment]
I think the problem is twofold. First, indeed, pyvisa needs to be updated. Second, a simple:
```
$ conda install pyvisa-py
```
or an
```
$ conda update --all
```
will result in the pyvisa-py backend being unavailable (leading to a nonfunctional VISA installation). By specifying the correct version requirement of pyvisa-py (requiring `pyvisa >= 1.11`) should lead to the conda solver downgrading pyvisa-py resulting in a functional installation.

**Comment by MatthieuDartiailh** [comment]
Could I please be added as maintainer of the feedstock since I am the current maintainer of pyvisa-py . Pyvisa 1.11 is now available on conda and only the tests for the recipe need to be updated.

**Comment by mtsolmn** [comment]
Thanks for your patience while we got things ironed out. Should be working now.

@MatthieuDartiailh You've been added as a maintainer, thanks for asking to help. If you see anything in the recipe that should be fixed, feel free, particularly to check I'm running all the right tests. Additionally, I've set the python requirement to >=3.6 to satisfy linting requirements; let me know if this is wrong. Thanks.

**Comment by MatthieuDartiailh** [comment]
Thabks for adding me.

The requirement on Python is fine I dropped support for anything older than 3.6. Regarding the tests, pyvisa now use pytest and I should update pyvisa-py to do more obviously the same. But anyway testing pyvisa-py is virtually impossible without an instrument so I thing the import tests are sufficient.

**Comment by davidfokkema** [comment]
Thanks for merging this!
