### ISSUE TITLE
UserWarning about pre-link script

### ISSUE THREAD

**Issue by bilderbuchi** [conda-forge/pyvisa-py-feedstock#7]
When updating my packages, I noticed the following warning:

> UserWarning: Package conda-forge::pyvisa-py-0.2-py_1000 uses a pre-link script. Pre-link scripts are potentially dangerous.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.

This is on Windows using conda 4.5.11 and pyvisa-py-0.2-py_1000. I'm not sure if more info than that is relevant.

Honestly I don't know if this is a spurious/false-positive warning, if the pre-link script can be avoided, or where it even is located (as I could not find anything related in the recipe folder).

**Comment by bilderbuchi** [comment]
So, this still happens with pyvisa-py-0.3.1-py_0, but there is no script to be found anywhere in the feedstock repo, but curiously if one downloads one of the generated packages [here](https://anaconda.org/conda-forge/pyvisa-py/files), there is a link.py and pre-link scripts in the package. 
Does anybody know how/why the pre-link scripts are generated? Is this a conda-smithy problem?

**Comment by bilderbuchi** [comment]
Hmm, I just realised that this is not building noarch packages despite having `noarch_python: True` in the [recipe](https://github.com/conda-forge/pyvisa-py-feedstock/blob/5f031b49912d077445be579bb47efcf769c1ac73/recipe/meta.yaml#L15). 
I think [this should be](https://conda-forge.org/docs/meta.html#building-noarch-packages) `noarch: python` instead (although I can only find [few mentions](https://github.com/conda-forge/conda-smithy/issues/485#issuecomment-309289202) of this). @mariusvniekerk @bgruening @greyltc do you know anything about this?

**Comment by bilderbuchi** [comment]
@conda-forge-admin, please rerender

**Comment by jamienoss** [comment]
For conda 4.7.11 this has become an actual blocker for me when creating an env from an environment file. 

```
LinkError: pre-link script failed for package conda-forge::pyvisa-py-0.3.1-py_0
location of failed script: /Users/me/anaconda3/pkgs/pyvisa-py-0.3.1-py_0/bin/.pyvisa-py-pre-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
...
```

Ending in the actual error:
```
+ /Users/me/anaconda3/envs/hicat-package/bin/python /Users/me/anaconda3/pkgs/pyvisa-py-0.3.1-py_0/link.py
/Users/me/anaconda3/pkgs/pyvisa-py-0.3.1-py_0/bin/.pyvisa-py-pre-link.sh: line 2: /Users/me/anaconda3/envs/hicat-package/bin/python: No such file or directory

return code: 127
```
This looks like a dependency sequence issue in that the pre-link is happening _before_ python has been installed in the env.
https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html states that pre-link scripts occur before the package is installed not the entire env, so this _should_ work. Actually, it also states that pre-link scripts should:
>Not depend on any installed or to-be-installed conda packages.

I can't see anything at https://docs.conda.io/projects/conda/en/latest/release-notes.html indicating that pre-link scripts have been deprecated.

I can install pyvisa-py to an existing env containing python.

I don't know whether this could be some other bug in conda, some change in conda that unknowingly deprecates pre-link scripts, or and issue with this recipe, as noted above.

**Comment by jamienoss** [comment]
Bingo: https://www.anaconda.com/condas-new-noarch-packages/

**Comment by jamienoss** [comment]
https://github.com/conda/conda/blob/master/conda/core/link.py#L1134-L1140

**Comment by bilderbuchi** [comment]
@jamienoss I have prepared PR #9, maybe this solves the problem?
